services:
  - type: web
    name: moodify-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        value: https://moodify-backend.onrender.com/callback
      - key: POST_LOGIN_REDIRECT
        value: https://moodify-ai-powered.vercel.app